### ISSUE TITLE
[BUG-달력페이지] Header의 달력 아이콘 배경색이 두번 클릭해야만 변경되고 querySelector null 오류가 발생합니다

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-2#43]
## 버그를 설명해주세요!

Header의 달력 아이콘 배경색이 두번 클릭해야만 변경되고 querySelector null 오류가 발생합니다.

## 어떤 상황에서 버그가 발생했나요?
버그가 발생한 상황은 다음과 같습니다.:
1. 배포된 버전으로 접속
2. 헤더의 달력 아이콘 클릭
테스팅 환경은 "Chrome"입니다.

## 어떻게 고쳐야할까요?

해결 방법에 대해서 리뷰 남겨봤습니다 ㅎㅎ 확인해주세요~ 

- #40 [리뷰](https://github.com/woowa-techcamp-2021/cashbook-2/pull/40#discussion_r680020592)
- #39 [리뷰](https://github.com/woowa-techcamp-2021/cashbook-2/pull/39#discussion_r680017162)

## 에러 화면

![2021-07-31 00 42 22](https://user-images.githubusercontent.com/75124422/127677800-522ebc35-7d82-4212-b1a3-5af4180d4f0c.gif)

## 추가

사실 남길까말까 고민하다가 오늘 코드 리뷰 시간도 있었고 해서 살펴보다가 남겨보면 좋을 것 같다는 생각에 남겨봅니다 ㅎㅎ 제가 잘못 알고 남긴 거일 수도 있는 데 넓은 아량으로 이해해주시면 좋겠습니다 ㅠㅠㅠ 이미 수정하신 부분일까 걱정되네요 ㅠㅠㅠㅠ

**Comment by sshrik** [comment]
해당 부분 확인하여 수정했습니다. 친절한 리뷰 감사해요!ㅎㅎ
